insert into codigo_irregularidade (codigo,descricao) values ('01','Despesas sem prévio-empenho');
insert into codigo_irregularidade (codigo,descricao) values ('02','Despesas sem comprovante legal');
insert into codigo_irregularidade (codigo,descricao) values ('03','Comprovantes rasurados');
insert into codigo_irregularidade (codigo,descricao) values ('04','Documentos faltando assinatura');
insert into codigo_irregularidade (codigo,descricao) values ('05','Despesas classificadas incorretamente');
insert into codigo_irregularidade (codigo,descricao) values ('06','Histórico incompleto');
insert into codigo_irregularidade (codigo,descricao) values ('07','Falta indicação de processo de compra'); 
insert into codigo_irregularidade (codigo,descricao) values ('08','Nota fiscal ou comprovante vencido');
insert into codigo_irregularidade (codigo,descricao) values ('09','Despesas c/ viagem s/ autorização legal');
insert into codigo_irregularidade (codigo,descricao) values ('10','Falta liquidação na nota fiscal');
insert into codigo_irregularidade (codigo,descricao) values ('11','Quitação anterior ao documento fiscal');
insert into codigo_irregularidade (codigo,descricao) values ('12','Nome fornecedor diverge entre NE e NF');
insert into codigo_irregularidade (codigo,descricao) values ('13','Valor do comprovante diverge da NE');
insert into codigo_irregularidade (codigo,descricao) values ('14','Verificar a incidência de descontos');
insert into codigo_irregularidade (codigo,descricao) values ('15','Natureza operação diverge do tipo de NF');
insert into codigo_irregularidade (codigo,descricao) values ('16','Despesa com publicidade s/comprovante');
insert into codigo_irregularidade (codigo,descricao) values ('(17','Despesa não afeta ao município');
insert into codigo_irregularidade (codigo,descricao) values ('18','Campo Data sem preenchimento');
insert into codigo_irregularidade (codigo,descricao) values ('19','CNPJ do empenho diverge do CNPJ'); 
insert into codigo_irregularidade (codigo,descricao) values ('20','Despesas sem comprovante de quitação');
insert into codigo_irregularidade (codigo,descricao) values ('21','Tipo de empenho incorreto');
insert into codigo_irregularidade (codigo,descricao) values ('22','Nota de empenho rasurada');
insert into codigo_irregularidade (codigo,descricao) values ('23','Empenho com data irregular');                                  
insert into codigo_irregularidade (codigo,descricao) values ('24','Despesa irregular');